let r = String.raw; // raw string tag for convenient LateX/KaTeX

function renderMath() {
  renderMathInElement(document.body, {
    // ...options...
    delimiters: 
    [
      {left: r`\[`, right: r`\]`, display: true},
      {left: r`\(`, right: r`\)`, display: false},
    ],
    macros: {
      "\\Z": r`\mathbb Z`,
      "\\R": r`\mathbb R`,
      "\\Aut": r`\operatorname{Aut}`,
      "\\Inn": r`\operatorname{Inn}`,
      "\\Sym": r`\operatorname{Sym}`,
      "\\inv": r`^{-1}`,
    }
  });
}

function pick(questions, element) {
  element.innerHTML = "<b> Problem. </b>" + questions[Math.floor(Math.random() * questions.length)];
  renderMath();
}

function showAll(questions, element) {
  element.innerHTML = "<b> Problem. </b>" + questions.reduce((acc, cur) => acc + "</br></br></br></br></br> <b> Problem. </b>" + cur);
  renderMath();
}

function createList(type, ...strings) {
  let template = `<ol type=${type}>`
  template += strings.map(s => `<li>${s}</li>`).reduce((acc, cur) => acc + cur);
  template += `</ol>`
  return template;
}

// Add KaTeX.js rendering to the whole document
document.addEventListener("DOMContentLoaded", () => renderMath());

let questions = [
  r`Describe all the subgroups of \( \Z \).`,
  r`Let \( G \) be a group and \( S \subseteq G \) be a nonempty subset.` + "\n"
  + r`Write \( S_\pm := S \cup S \)` + "\n"
  + createList(1,
    r`Describe \( S_\pm^n \) for \( G = \Z \) and \( S = \{ 1 \} \)`,
    r`Show that the set \[ \langle S \rangle := \bigcup_{n \geq 1} S_\pm^n \] is a subgroup of \( G \).`,
    r`Show that \( \langle S \rangle \) is the smallest subgroup of \( G \) containing \( S \), i.e. \[ \langle S \rangle = \bigcap_{H \subseteq S} H. \]`,
  ),
  r`Describe all the groups generated by 2 elements, such that every non trivial element is an involution.`,
  r`Show that every cancellative finite semigroup is a group.`,
  r`Prove Lagrange's theorem.`, // end of assignment 1
  createList(1, r`Describe the subgroups of \( \Z / n\Z \)`, r`Show that \( \sum_{k\; | \; n} \varphi(k) = n \).`),
  createList(1,
    r`Show that a finite cyclic group contains at most one element of order 2.`,
    r`Let \( k \geq 1 \). Show that \( 5^{2^k} = 1 + 2^{k+2}m \) where \( m \) is an odd number.`,
    r`Let \( k \geq 2 \). Compute the order of 5 in \( (\Z / 2^k \Z)^\times \).`,
    r`Let \( k \geq 3 \). Show that \( 5^{2^{k-3}} \neq 1 \; \mathrm{mod} \; 2^k \).`,
    r`Show that \( (\Z / 2^k\Z)^\times \) is generated by 2 elements. When can it be generated by a single element?`,
  ),
  r`Show that \( Q \) is not finitely generated.`,
  r`Show that if \( w \) is a word, or more generally \( W \) is a set of words, then the subgroup \( \langle S \rangle \) of \( G \) `
  + r`generated by the set \( S \) obtained by substituting the letters in \( w \) (or in the set of \( w \in W \)) by elements in \( G \) is characteristic.`,
  createList(1,
    r`Show that every subgroup of \( \Z/n\Z \) is characteristic (so for \( \Z/n\Z \), simple \( \iff \) characteristically simple \( \iff \) \( n \) prime).`,
    r`Let \( p \) be a prime number. Show that \( \operatorname{GL}_n(\Z/p\Z) \) acts transitively on \( (\Z/p\Z) \setminus \{ (0, \ldots 0,)\} \), and `
    + r`that \( (\Z/p\Z)^n \) is characteristically simple.`,
    r`Let \( G \) be a finite group. Show that if \( \Aut(G) \) acts transitively on \( G \setminus \{ e \} \), then \( G \) is elementary abelian.`,
  ),
  r`Let \( G \) be a group.`
  + createList(1,
    r`Show that if \( G/Z(G) \) is singly generated, then \( G \) is abelian`,
    r`Show that if \( \Inn(G) \) is singly generated, then it must be the trivial group.`
  ), // end of assignment 2
  createList(1,
    r`Write every cycle of odd length greate than 5 as a product of 3-cycles.`,
    r`Show that the set of 3-cycles is a generating set of \( A_n \).`
  ),
  r`Compute the center of \( D_n \).`,
  createList(1,
    r`Prove from first principles that the identity permutation can only be written as a product of an even number of transpositions`,
    r`Deduce from (1) that`
    + createList("a", r`the parity of a permutation is well defined, and`, r`the signature is a group homomorphism.`)
  ),
  createList(1,
    r`Show if \( \tau \in S_n \) is arbitrary and \( \sigma = (a, b, d, c, e) \in S_n \) is a \( k \)-cycle, then`
    + r`\[ \tau \sigma \tau\inv = (\tau(a), \tau(b), \tau(c), \tau(d), \tau(e), \ldots)  .\]`,
    r`Two permutations are said to have congruent cycle decomposition if they have the same number of \( k \)-cycles for every \( k \). `
    + r`Show that two permutations \( \sigma, \sigma' \) have congruent cycle decompositions if and only if they are conjugate, i.e., there exists `
    + r`\( \tau \) such that \( \sigma' = \tau \sigma \tau\inv \).`
  ),
  createList(1,
    r`Show that there are two conjugacy classes of 5-cycles in \( A_5 \).`,
    r`Show that the following conditions are equivalent:`
    + createList("a",
      r`the \( S_n \)-conjugacy classes of a permutation \( \sigma \) in \( A_n \) does not split into two \( A_n \) classes`,
      r`there exists an odd permutation which commutes to \( \sigma \).`
    ),
    r`Show that the following conditions are equivalent:`,
    createList("a",
      r`The \( S_n \)-class decomposition of \( \sigma \) is a product of cycles of pairwise distinct odd lengths `
      + `(where, for example, a pair of fixed points is considered to be a product of two cycles of length 1).`
    ),
  ), // end of assignment 3
  r`Let \( G \) be a group of even order. Show from first principles that \( G \) contains an element of order 2.`,
  r`Let \( G \) be a group. `
  + r`Describe the centralizer and the normalizer in \( \Sym(G) \) of the image of \( G \) under the left regular action \( G \to \Sym(G) \).`,
  r`Let \( G \) be a group of order \( 2p \) where \( p \) is an odd number. `
  + r`Let \( G \to \Sym(G) \) be the Cayley action. Show that the image of \( G \) in \( \Sym(G) \) contains an odd permutation. `
  + r`Deduce that \( G \) contains a normal subgroup of index 2.`,
  r`Let \( G \) be a semigroup, \( S \subseteq G \) be a set, and let \( S' \) denote the commutant (or centralizer) of \( S \) in \( G \). `
  + r`Show that \( S' \) is a semigroup. Show that \( S''' = S' \).`,
  r`Draw a Cayley graph of \( A_4 \) in which one can see the Klein group \( V \lhd S_4 \) and its 3 cosets.`, // end of assignment 4
]

window.onload = () => {
  let questionP = document.querySelector("#question-p");
  let nextButton = document.querySelector("#next-button");
  let showAllButton = document.querySelector("#show-all-button");
  pick(questions, questionP);

  nextButton.onclick = () => pick(questions, questionP);
  showAllButton.onclick = () => showAll(questions, questionP);
}
