const r = String.raw; // raw string tag for convenient LateX/KaTeX

function createList(type, ...strings) {
  return `<ol type=${type}>${strings.map(s => `<li>${s}</li>`).reduce((a, c) => a + c)}</ol>`;
}

const questions = [
[
  r`Describe all the subgroups of \( \Z \).`,
  r`Let \( G \) be a group and \( S \subseteq G \) be a nonempty subset.` + "\n"
  + r`Write \( S_\pm \coloneqq S \cup S\inv \).`
  + createList(1,
    r`Describe \( S_\pm^n \) for \( G = \Z \) and \( S = \{ 1 \} \).`,
    r`Show that the set \[ \langle S \rangle := \bigcup_{n \geq 1} S_\pm^n \] is a subgroup of \( G \).`,
    r`Show that \( \langle S \rangle \) is the smallest subgroup of \( G \) containing \( S \), i.e. \[ \langle S \rangle = \bigcap_{H \subseteq S} H. \]`,
  ),
  r`Describe all the groups generated by 2 elements, such that every non trivial element is an involution.`,
  r`Show that every cancellative finite semigroup is a group.`,
  r`Prove Lagrange's theorem.`, // end of assignment 1
  createList(1, r`Describe the subgroups of \( \Z / n\Z \)`, r`Show that \( \sum_{k\; | \; n} \varphi(k) = n \).`),
  createList(1,
    r`Show that a finite cyclic group contains at most one element of order 2.`,
    r`Let \( k \geq 1 \). Show that \( 5^{2^k} = 1 + 2^{k+2}m \) where \( m \) is an odd number.`,
    r`Let \( k \geq 2 \). Compute the order of 5 in \( (\Z / 2^k \Z)^\times \).`,
    r`Let \( k \geq 3 \). Show that \( 5^{2^{k-3}} \neq 1 \; \mathrm{mod} \; 2^k \).`,
    r`Show that \( (\Z / 2^k\Z)^\times \) is generated by 2 elements. When can it be generated by a single element?`,
  ),
  r`Show that \( \Q \) is not finitely generated.`,
  r`Show that if \( w \) is a word, or more generally \( W \) is a set of words, then the subgroup \( \langle S \rangle \) of \( G \) `
  + r`generated by the set \( S \) obtained by substituting the letters in \( w \) (or in the set of \( w \in W \)) by elements in \( G \) is characteristic.`,
  createList(1,
    r`Show that every subgroup of \( \Z/n\Z \) is characteristic (so for \( \Z/n\Z \), simple \( \iff \) characteristically simple \( \iff \) \( n \) prime).`,
    r`Let \( p \) be a prime number. Show that \( \operatorname{GL}_n(\Z/p\Z) \) acts transitively on \( (\Z/p\Z) \setminus \{ (0, \ldots, 0)\} \), and `
    + r`that \( (\Z/p\Z)^n \) is characteristically simple.`,
    r`Let \( G \) be a finite group. Show that if \( \Aut(G) \) acts transitively on \( G \setminus \{ e \} \), then \( G \) is elementary abelian.`,
  ),
  r`Let \( G \) be a group.`
  + createList(1,
    r`Show that if \( G/Z(G) \) is singly generated, then \( G \) is abelian`,
    r`Show that if \( \Inn(G) \) is singly generated, then it must be the trivial group.`
  ), // end of assignment 2
  createList(1,
    r`Write every cycle of odd length greater than 5 as a product of 3-cycles.`,
    r`Show that the set of 3-cycles is a generating set of \( A_n \).`
  ),
  r`Compute the center of \( D_n \).`,
  createList(1,
    r`Prove from first principles that the identity permutation can only be written as a product of an even number of transpositions`,
    r`Deduce from (1) that`
    + createList("a", r`the parity of a permutation is well defined, and`, r`the signature is a group homomorphism.`)
  ),
  createList(1,
    r`Show if \( \tau \in S_n \) is arbitrary and \( \sigma = (a, b, d, c, e) \in S_n \) is a \( k \)-cycle, then`
    + r`\[ \tau \sigma \tau\inv = (\tau(a), \tau(b), \tau(c), \tau(d), \tau(e), \ldots)  .\]`,
    r`Two permutations are said to have congruent cycle decomposition if they have the same number of \( k \)-cycles for every \( k \). `
    + r`Show that two permutations \( \sigma, \sigma' \) have congruent cycle decompositions if and only if they are conjugate, i.e., there exists `
    + r`\( \tau \) such that \( \sigma' = \tau \sigma \tau\inv \).`
  ),
  createList(1,
    r`Show that there are two conjugacy classes of 5-cycles in \( A_5 \).`,
    r`Show that the following conditions are equivalent:`
    + createList("a",
      r`the \( S_n \)-conjugacy classes of a permutation \( \sigma \) in \( A_n \) does not split into two \( A_n \) classes`,
      r`there exists an odd permutation which commutes to \( \sigma \).`
    ),
    r`Show that the following conditions are equivalent:`
    + createList("a",
      r`the \( S_n \)-class of a permutation \( \sigma \) in \( A_n \) splits into two \( A_n \)-classes`,
      r`the cycle decomposition of \( \sigma \) is a product of cycles of pairwise distinct odd lengths`
    ),
  ), // end of assignment 3
  r`Let \( G \) be a group of even order. Show from first principles that \( G \) contains an element of order 2.`,
  r`Let \( G \) be a group. `
  + r`Describe the centralizer and the normalizer in \( \Sym(G) \) of the image of \( G \) under the left regular action \( G \to \Sym(G) \).`,
  r`Let \( G \) be a group of order \( 2p \) where \( p \) is an odd number. `
  + r`Let \( G \to \Sym(G) \) be the Cayley action. Show that the image of \( G \) in \( \Sym(G) \) contains an odd permutation. `
  + r`Deduce that \( G \) contains a normal subgroup of index 2.`,
  r`Let \( G \) be a semigroup, \( S \subseteq G \) be a set, and let \( S' \) denote the commutant (or centralizer) of \( S \) in \( G \). `
  + r`Show that \( S' \) is a semigroup. Show that \( S''' = S' \).`,
  r`Draw a Cayley graph of \( A_4 \) in which one can see the Klein group \( V \lhd S_4 \) and its 3 cosets.`, // end of assignment 4
  r`Let \( S_4 \) denote the symmetric group on 4 elements.`
  + createList(1,
    r`Show that the Klein group \( V \) is a normal subgroup of \( S_4 \).`,
    r`Deduce that there exists a surjective homomorphism \( f : S_4 \surject S_3 \).`,
    r`Find \( \ker f \).`
  ),
  r`Let \( K, H \) be groups.`
  + createList(1,
    r`Show that \( K \rtimes H \) is a group.`,
    r`Show that the inclusions \( i : K \inject K \rtimes H \) and \( j : H \inject K \rtimes H \) are group homomorphisms.`
  ),
  r`Let \( p, q \) be integers.`
  + createList(1,
    r`Find a short exact sequence \[ \Z / p\Z \inject \Z / pq \Z \surject \Z / q\Z. \]`,
    r`Show that the sequence splits if and only if \( p, q \) are coprime.`
  ),
  r`Let \( n \geq 3 \). Show that the dihedral group \( D_n \), and the symmetric group \( S_n \), are non trivial semidirect products.`,
  r`Let \( A, B \) be normal subgroups generating a group \( G \), i.e., \( G = \langle A, B \rangle \).`
  + r` Show that \( G / (A \cap B) \isom G / A \times G / B \).`, // end of assignment 5
  r`Is \( Q_8 \), the group of quaternions, a nontrivial semidirect product?`,
  r`Show that the dihedral group \( D_n \) is nilpotent if and only if \( n \) is a power of 2.`,
  r`Let \( G \) be a finite group. Suppose that there exists \( \sigma \in \Aut(G) \) such that \( \sigma^2 = \mathrm{Id} \) and \( \sigma(s) \neq s \) `
  + r`for every \( s \in G \) distinct from \( e \). Show that \( G \) is abelian.`,
  r`Given a finite group \( G \), the Frattini subgroup \( \Phi \) of \( G \) is defined to be the intersection of all maximal subgroups of \( G \).`
  + createList(1,
    r`Show that \( \Phi \) is normal in \( G \).`,
    r`Show that if \( H < G \) , then \( \Phi H < G \).`,
    r`Let \( H \) be a Sylow subgroup of \( \Phi \). Show that \( \Phi N_G(H) = G \).`,
    r`Deduce from (2) and (3) that \( \Phi \) is nilpotent.`
  ),
  r`Let \( f \) be an automorphism of the symmetric group \( S_n \). If \( f \) is inner then it preserves the \( k \)-cycles, for every \( k \geq 2 \), `
  + r`by the usual conjugacy formula. The exercise is to prove that the converse is true; more generally, prove that if \( f \) takes the transpositions to `
  + r`transpositions, then \( f \) is inner.`, // end of assignment 6
  r`Let \( p \) be a prime number, and \( G \) be a finite group acting faithfully and transitively on a set \( X \) with \( p \) elements. `
  + r`Show that every nontrivial normal subgroup of \( G \) acts transitively on \( X \).`,
  r`Let \( p \) be a prime number.`
  + createList(1,
    r`How many Sylow \( p \)-subgroups are there in \( S_p \)?`,
    r`Deduce that \( (p-1)! \equiv -1 \mod p \).`
  ),
  r`Work out \( \operatorname{Sylow}(35) \).`,
  createList(1,
    r`Show that every maximal subgroup of a finite abelian group is of prime index.`,
    r`Show the same thing for finite nilpotent groups.`
  ),
  r`Let \( G \) be a simple group of order 168. How many elements of order \( 7 \) are there in \( G \)?` // end of assignment 7
],
// Analysis
[
r`
For every set \( A \subset \R \), let \( m^*_J(E) \) be defined as
\[ m^*_J(A) = \inf \sum_{k=1}^n \ell(I_k), \]
where the infimum is taken over all finite coverings of
  \( E \) by open intervals \( I_k \).
` + createList(1,
  r`
  Prove that \( m^*_J(A) = m^*J(\overline{A}) \) for all sets
  \( A \subset \R \) where \( \overline A \) denotes the closure of \( A \).
  `,
  r`
  Give an example of a countable set \( A \) such that
  \( m^*_J(A) = 1 \). Compare with \( m^*(A) \).
  `,
),
r`
A set of real numbers is said to be a \( G_\delta \) set provided it is
intersection of a countable collection of open sets.
Show that for any set \( A \subseteq \R \) such that \( m^*(A) < \infty \),
there is a \( G_\delta \) set \( G \) for which \( A \subset G \) and
\( m^*(G) = m^*(A) \).
`,
r`
Show that continuity of measure together with finite additivity of measure
implies countable additivity of measure.
`,
r`
Let \( A, B \subset \R \) be such that \( A \) and \( B \) are
measurable and \( m(A) = m(B) < \infty \). Prove that every set \( E \)
such that \( A \subset E \subset B \) is measurable.
`,
r`
Let \( A \subset \R, \) \( \alpha > 0 \) and
\( A_\alpha = \set{ax : x \in A} \).
` + createList(1,
  r`
  Prove that \( m^*(A_\alpha) = \alpha m^*(A) \).
  `,
  r`
  Prove that \( A \) is measurable if and only if \( A_\alpha \) is
  measurable.
  `,
),
r`
Let \( A \subset \R \) and
\( O_n = \set{x \in \R : d(x, A) = 1/n} \) for all \( n \in \N \), where
\( d(x, A) = \inf \set{\abs{x - y} : y \in A} \).
` + createList(1,
  r`
  Prove that if \( A \) is compact then
  \[ \lim_{n \to \infty} m(O_n) = m(A). \]
  `,
  r`
  Prove that this is not necessarily true if \( A \) is open and bounded.
  `,
), // end of assignment 1
r`
Let \( A \) and \( B \) be two subsets of \( A \) and \( A + B \) be the
set defined by \( A + B = \set{x + y : x \in A ,\, y \in B} \).
Prove that:
` + createList(1,
  r`
  If \( A \) is closed and \( B \) is compact, then \( A + B \) is closed.
  `,
  r`
  If \( A \) and \( B \) are measurable, then \( A + B \) is measurable.
  `,
),
r`,
Let \( A \subset \R \) be measurable. Prove that
\[ m(A) = \sup\set{m(K) \given K \subset A,\, K\ \text{compact}}. \]
`,
r`
Let \( A \) be a subset of \( \R \) such that \( m^*(A) < \infty \).
Prove that:
` + createList(1,
  r`
  \( A \) is measurable if and only if there exists an
  \( F_\sigma \) set \( F \) such that \( F \subset A \) and 
  \( m(F) = m^*(A) \).
  `,
  r`
  \( A \) is non-measurable if and only if there exists a \( G_\delta \)
  set \( G \) such that \( A \subset G \), \( m(G) = m^*(A) \) and
  \( m(G \setminus A) > 0 \).
  `,
),
createList(1,
  r`
  Show that a strictly increasing function that is defined on an interval
  has continuous inverse.
  `,
  r`
  Let \( A \) and \( B \) be two Borel subsets of \( \R \) and 
  \( f : A \to \R \) be a continuous function.
  Show that \( f \inv(B) \) is a Borel set.
  `,
  r`
  Show that a continuous strictly increasing function that is defined on
  an interval maps Borel sets to Borel sets.
  `,
),
createList(1,
  r`
  Prove that every closed set is a \( G_\delta \) set and every 
  open set is an \( F_\sigma \) set.
  `,
  r`
  Prove that \( \Q \) is an \( F_\sigma \) set but not a \( G_\delta \) set.
  `,
), // end of assignment 2
r`
A function \( f : \R \to \overline R \) is said to be Borel measurable
provided its domain \( A \subset \R \) is a Borel set, and for each \( c \),
the set \( \set{x \in A : f(x) < c} \) is a Borel set.
Prove that:
` + createList(1,
  r`
  Every Borel measurable function is Lebesgue measurable.
  `,
  r`
  If \( f \) is Borel measurable and \( B \) is a Borel set,
  then \( f \inv (B) \) is a Borel set.
  `,
  r`
  If \( f \) and \( g \) are Borel measurable, so is \( f \of g \).
  `,
  r`
  If \( f \) is Borel measurable and \( g \) is Lebesgue measurable, then
  \( f \of g \) is Lebesgue measurable.
  `,
),
r`
Let \( (f_n)_{n \in \N} \) be a sequence of measurable functions
defined on a measurable set \( A \subset \R \).
Let \( A_0 \) be the set of points in \( x \) at which
\( (f_n(x))_{n \in \N} \) converges.
Is the set \( A_0 \) measurable?
`,
r`
Let \( (f_n)_{n \in \N} \) be a sequence of measurable functiosn defined on
a measurable set \( A \subset \R \).
Prove that each of the following functions are measurable:
\[ \inf_{n \in \N} (f_n), \quad \sup_{n \in \N}(f_n),
\quad \liminf_{n \to \infty} (f_n) \quad \text{and} \quad
\limsup_{n \to \infty} (f_n). \]
`,
createList(1,
  r`
  Show that the conclusion of Egoroff's Theorem can fail is we drop
  the assumption that the domain has finite measure.
  `,
  r`
  Show that Lusin's Theorem holds
  if the domain has infinite measure using the
  fact that it holds if the domain has finite measure.
  `,
),
r`
Let \( f \) and \( g \) be two bounded measurable functions defined on
a set of finite measure \( A \subset \R \).
Prove that if \( f = g \) a.e. in \( A \), then \( \int_A f = \int_A g \).
`,
r`
Let \( f \) be a bounded measurable function defined on a set of
finite measure \( A \subset \R \).
Prove that:
` + createList(1,
  r`
  If \( \int_B f \geq 0 \) for all measurable sets \( B \subset A \), then
  \( f \geq 0 \) a.e. in \( A \).
  `,
  r`
  If \( \int_B f = 0 \) for all measurable sets \( B \subset A \), then
  \( f = 0 \) a.e in \( A \).
  `,
), // assignment 3 done
r`
Suppose \( f \) is measurable on \( \R \), finite almost everywhere,
and \( f \geq 0 \). Let \( F_k = \set{x : 2^k < f(x) \leq 2^{k+1}} \).
Prove that:
\[ f\ \text{is integrable on}\ \R \iff
\sum_{k=-\infty}^{+\infty} 2^k m(F_k) < \infty. \]
Then, verify that
\[ f(x) = \begin{cases} \abs{x}^{-a} & \text{if}\ \abs{x} \leq 1 \\
0 & \text{otherwise} \end{cases} \]
is integrable over \( \R \) if and only if \( a < 1 \) and
\[ g(x) = \begin{cases} \abs x ^{-b} &\text{if}\ \abs{x} > 1 \\
0 &\text{otherwise} \end{cases} \]
is integrable over \( \R \) if and only if \( b > 1 \).
`,
createList(1,
  r`
  Let \( (f_n)_{n \in \N} \) be a sequence of nonegative measurable functions
  over \( A \subset \R \). Prove that if \( f_1 \) is integrable over \( A \)
  and \( f_{n+1} < f_N \) for all \( n \in \N \), then
  \[ \lim_{n\to\infty} \int_A f_n = \int_A \lim_{n \to \infty} f_n . \]
  `,
  r`
  Show by providing a counter-example that this assertion is not true
  in general when \( f_1 \) is not integrable over \( A \).
  `,
),
r`
Let \( f \) be a real-valued function of two variables \( (x, y) \) that
is defined on the square \( [0,1] \times [0,1] \).
Suppose that \( x \to f(x, y) \) is integrable over \( [0,1] \) for each fixed
value of \( y \). Let \( h \) be the function of \( y \) defined by
\[ h(y) = \int_{[0,1]} f(x, y)\; dx. \]
` + createList(1,
  r`
  Sppose that for each \( (x, y) \) , we have \( \abs{f(x,y)} \leq g(x) \),
  where \( g \) is integrable over \( [0,1] \).
  Prove that if \( f(x, y) \) is continuous in \( y \) for each \( x \),
  then \( h \) is continuous.
  `,
  r`
  Suppose that for each \( (x, y) \),
  \[ \frac{\partial f}{\partial y} (x, y)\ \text{exists and}\ 
  \abs{\frac{\partial f}{\partial y} (x, y)} \leq g(x), \]
  where \( g \) is integrable over \( [0,1] \).
  Prove that \( h \) is differentiable and
  \[ h'(y) = \int_{[0,1]} \frac{\partial f}{\partial y} (x, y)\; dx. \]
  `,
),
createList(1,
  r`
  Let \( f \) be integrable over \( A \subset \R \).
  By using the countable additivity of integration, prove that:
  ` + createList('a',
    r`
    If \( (A_n)_{n\in\N} \) is a sequence of measurable subsets of \( A \)
    such that \( A_{n+1} \subset A_n \) for all \( n \in \N \), then
    \[ \int_{\bigcup_{n=1}^\infty A_n} f = \lim_{n \to \infty} \int_{A_n} f. \]
    `,
    r`
    If \( (A_n)_{n \in \N} \) is a sequence of measurable subsets of \( A \)
    such that \( A_n \subset A_{n+1} \) for all \( n \in \N \), then
    \[ \int_{\bigcap_{n=1}^\infty A_n} f = \lim_{n\to\infty} \int_{A_n} f. \]
    `,
  ),
  r`
  Prove that if \( f \) is integrable over \( \R \), then
  \( \displaystyle F(x) = \int_{(-\infty, x)} f \)
  is continuous in \( \R \) and satisfies
  \( \displaystyle \lim_{x \to -\infty} F(x) = 0 \) and 
  \( \displaystyle \lim_{x\to+\infty} F(x) = \int_\R f. \)
  `,
  r`
  Let \( \displaystyle f(x) = \frac{\sin(x)}x \) for all
  \( x \in [\pi, \infty) \).
  Prove that \( \displaystyle \lim_{n\to\infty} \int_{\pi,n\pi} f \) exists,
  while \( f \) is not integrable over \( [\pi, \infty) \).
  `,
),
r`
Determine the limit as \( n \to \infty \) of the numbers
\[ I_n = \int_{(0,\infty)} \frac{x^n}{1 + x^{n+2}}\; dx. \]
`, // end of assignment 4
r`
Let the function \( f \) be absolutely continuous on \( [a,b] \).
Prove that \( f \) is Lipschitz on \( [a,b] \) if and only if there is a
constant \( c > 0 \) for which \( \abs{f'} \leq c \) a.e. on \( [a,b] \).
`,
createList(1,
  r`
  Let \( f \) be Lipschitz on \( \R \) and \( g \) be absolutely continuous on
  \( [a,b] \). Prove that the composition \( f \of g \) is absolutely continuous
  on \( [a,b] \).
  `,
  r`
  Define the functions \( f \) and \( g \) on \( [0,1] \) by \( f(x) = x^{1/3} \)
  for \( 0 \leq x \leq 1 \) and
  \[ g(x) = \begin{cases} x^3 \cos(\pi/2x)^3 & \text{for}\ 0 < x \leq 1 \\
  0 & \text{for}\ x = 0. \end{cases} \]
  ` + createList('a',
    r`
    Prove that both \( f \) and \( g \) are absolutely continuous on \( [0,1] \).
    `,
    r`
    Prove that \( f \of g \) fails to be of bounded variation, and hence
    also fails to be absolutely continuous on \( [0,1] \).
    `,
  ),
),
r`
Let \( f \) fail to be of bounded variation on \( [a,b] \).
Show that there is a point \( x_0 \in [a,b] \) such that for every
\( \delta > 0 \), \( f \) fails to be of bounded varitation on the interval
\( [x_0 - \delta, x_0 + \delta] \cap [a,b] \).
`,
createList(1,
  r`
  Prove that both the sum and product of functions of bounded variation on an
  interval \( [a,b] \) are of bounded variation.
  `,
  r`
  Prove that both the sum and product of absolutely continuous functions
  on an interval \( [a,b] \) are absolutely continuous.
  `,
  r`
  Let \( f \) and \( g \) be absolutely continuous on \( [a,b] \).
  Prove that
  \[ \int_{[a,b]} fg' = f(b) g(b) - f(a)g(a) - \int_{[a,b]} f'g. \]
  `,
),
r`
Let \( f \) be of bounded variation on \( [a,b] \) and define
\( v(x) = \operatorname{TV}(f|_{[a,x]}) \) for all \( x \in [a,b] \).
` + createList(1,
  r`
  Prove that \( \abs{f'} \leq v' \) a.e. on \( [a,b] \) and infer
  from this that
  \[ \int_{[a,b]} \abs{f'} \leq \operatorname{TV}(f). \]
  `,
  r`
  Prove that the above is an equality if and only if \( f \) is
  absolutely continuous on \( [a,b] \).
  `,
), // end of assignment 5
r`
Suppose \( f \) is integrable over \( \R^d \).
For each \( \alpha > 0 \), let \( E_\alpha = \set{x : \abs{f(x)} > \alpha} \).
Prove that
\[ \int_{\R^d} \abs{f(x)}\; dx = \int_0^\infty m(E_\alpha)\; d\alpha. \]
`,
r`
Let \( \Gamma \subset \R^d \times \R \),
\( \Gamma = \set{(x,y) \in \R^d \times \R : y = f(x)} \), and assume
\( f \) is measurable on \( \R^d \).
Prove that \( \Gamma \) is a measurable subset of \( \R^{d+1} \), and
\( m(\Gamma) = 0 \).
`,
createList(1,
  r`
  Prove that if \( f \) is measurable on \( \R^d \), then
  \( (x, y) \to f(x-y) \) is measurable on \( \R^{2d} \).
  `,
  r`
  Prove that if \( f \) and \( g \) are integrable over \( \R^d \), then
  \( (x,y) \mapsto f(x-y) g(y) \) is integrable over \( \R^{2d} \).
  `,
  r`
  We define the convolution \( f * g \) of \( f \) and \( g \) as
  \[ (f*g)(x) = \int_{\R^d} f(x - y) g(y)\; dy. \]
  Prove that if \( f \) and \( g \) are integrable over \( \R^d \), then
  \( f*g \) is well-defined for a.e. \( x \).
  `,
  r`
  Prove that \( f*g \) is integrable whenever \( f \) and \( g \)
  are integrable and that
  \[ \int_{\R^d} \abs{(f*g)(x)}\; dx \leq
  \left ( \int_{\R^d} \abs{f(x)}\; dx \right )
  \left ( \int_{\R^d} \abs{g(x)}\; dx \right ) \]
  with equality if \( f \) and \( g \) are non-negative.
  `,
),
r`
Let \( C_0(\R^d) \) be the set of of continuous functions \( f : \R^d \to \R \)
such that \( \displaystyle \lim_{\abs{x} \to \infty} f(x) = 0 \), where
\( \abs{x} = \sqrt{\sum_{i=1}^n x_i^2} \).
` + createList(1,
  r`
  Prove that if \( f \) is uniformly continuous and integrable over \( \R^d \),
  then \( f \in C_0(\R^d) \).
  `,
  r`
  Prove that if \( f \) is bounded and uniformly continuous in \( \R^d \)
  and \( g \) is integrable over \( \R^d \), then
  \( f*g \) is well-defined and uniformly continuous in \( \R^d \).
  `,
  r`
  Prove that if both \( f \) and \( g \) are integrable over \( \R^d \)
  and \( f \) is bounded and uniformly continuous in
  \( \R^d \), then \( f*g \in C_0(\R^d) \).
  `,
),
r`
The Fourier transform of an integrable function \( f \) is defined as
\[ \hat f(\xi) =
\int_{\R^d} f(x) \cos(2\pi \langle x, \xi \rangle)\; dx
-i\int_{\R^d} f(x) \sin(2\pi \langle x, \xi \rangle)\; dx, \]
where \( \langle \cdot, \cdot \rangle \) stands for the inner product on
\( \R^d \).
Prove that for each \( \xi \) one has
\[ \widehat{f*g}(\xi) = \hat f(\xi) \hat g(\xi). \]
`,
],
[
"State the Simple Approximation Lemma.",
"State the Simple Approximation Theorem.",
"State the Bounded Convergence Theorem.",
"State Egoroff's Theorem.",
"Prove Chebyshev's Inequality and its corollaries.",
"Prove Fatou's Lemma, assuming the Bounded Convergence Theorem.",
"Prove the Monotone Convergence Theorem.",
"Prove the Dominated Convergence Theorem.",
`Prove the decomposition of functions of bounded variation as a
difference of two monotone functions.`,
`Prove the decomposition of absolutely continuous functions as a difference of two monotone,
absolutely continuous functions.`,
r`Prove the formula for the integral of a nonnegative measurable
function in terms of the measure of a region in \( \R^d \).`,
],
[
r`
Let \( X \sim U(0, 1) \).
Find \[ \E \left ( \left \lfloor \frac 1 X \right \rfloor \right ).\]
`,
r`
Let \( n \in \N \). Let \( A \) be a random \( n \times n \)
matrix such that \( A_{ij} \sim U(0, 1) \). Find \( \E[\det(A)] \)
as a function of \( n \).
`,
r`
Prove Bayes&#8217 theorem.
`,
],
];

